#!/usr/bin/env bash

rm -f ~/public_html/AMT/surveys/*
rm -f ~/public_html/AMT/codes/*
rm -f ~/public_html/AMT/target_commands/*
rm -f ~/public_html/AMT/validations/*
#rm -f src/log/*
#rm -f src/log_special/*
#rm -f src/executed_action/*
rm -f ~/public_html/AMT/log/*
rm -f ~/public_html/AMT/log_special/*
rm -f ~/public_html/AMT/executed_actions/*
